-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\Detect_Rise_Positive.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Detect_Rise_Positive
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/Mem_A/LIF_Neuron_Conductance/Detect Rise Positive
-- Hierarchy Level: 3
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Detect_Rise_Positive IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        U                                 :   IN    std_logic;
        Y                                 :   OUT   std_logic
        );
END Detect_Rise_Positive;


ARCHITECTURE rtl OF Detect_Rise_Positive IS

  -- Signals
  SIGNAL U_k                              : std_logic;
  SIGNAL U_k_1                            : std_logic;
  SIGNAL FixPt_Relational_Operator_out1   : std_logic;

BEGIN
  -- Edge
  -- U(k)

  
  U_k <= '1' WHEN U > '0' ELSE
      '0';

  -- 
  -- Store in Global RAM
  Delay_Input1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      U_k_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        U_k_1 <= U_k;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;


  
  FixPt_Relational_Operator_out1 <= '1' WHEN U_k > U_k_1 ELSE
      '0';

  Y <= FixPt_Relational_Operator_out1;

END rtl;

