-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\Detect_Rise_Positive_block.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Detect_Rise_Positive_block
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/P_A/LIF_Neuron_Conductance/Detect Rise Positive
-- Hierarchy Level: 3
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Detect_Rise_Positive_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        U                                 :   IN    std_logic_vector(9 DOWNTO 0);  -- boolean [10]
        Y                                 :   OUT   std_logic_vector(9 DOWNTO 0)  -- boolean [10]
        );
END Detect_Rise_Positive_block;


ARCHITECTURE rtl OF Detect_Rise_Positive_block IS

  -- Signals
  SIGNAL U_k                              : std_logic_vector(9 DOWNTO 0);  -- boolean [10]
  SIGNAL U_k_1                            : std_logic_vector(9 DOWNTO 0);  -- boolean [10]
  SIGNAL FixPt_Relational_Operator_out1   : std_logic_vector(9 DOWNTO 0);  -- boolean [10]

BEGIN
  -- Edge
  -- U(k)


  U_k_gen: FOR t_0 IN 0 TO 9 GENERATE
    
    U_k(t_0) <= '1' WHEN U(t_0) > '0' ELSE
        '0';
  END GENERATE U_k_gen;


  -- 
  -- Store in Global RAM
  Delay_Input1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      U_k_1 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        U_k_1 <= U_k;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;



  FixPt_Relational_Operator_out1_gen: FOR t_01 IN 0 TO 9 GENERATE
    
    FixPt_Relational_Operator_out1(t_01) <= '1' WHEN U_k(t_01) > U_k_1(t_01) ELSE
        '0';
  END GENERATE FixPt_Relational_Operator_out1_gen;


  Y <= FixPt_Relational_Operator_out1;

END rtl;

