-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\Enabled_Subsystem.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Enabled_Subsystem
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/Enabled Subsystem
-- Hierarchy Level: 1
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Enabled_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Spike                             :   IN    std_logic;
        Enable                            :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(11999 DOWNTO 0)  -- boolean [12000]
        );
END Enabled_Subsystem;


ARCHITECTURE rtl OF Enabled_Subsystem IS

  -- Signals
  SIGNAL enb_gated                        : std_logic;
  SIGNAL Enable_out2                      : std_logic;
  SIGNAL Tapped_Delay_out1                : std_logic_vector(11999 DOWNTO 0);  -- boolean [12000]
  SIGNAL Tapped_Delay_out1_bypass         : std_logic_vector(11999 DOWNTO 0);  -- boolean [12000]
  SIGNAL Tapped_Delay_out1_last_value     : std_logic_vector(11999 DOWNTO 0);  -- boolean [12000]

BEGIN
  Enable_out2 <= Enable;

  enb_gated <= Enable_out2 AND enb;

  Tapped_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Tapped_Delay_out1 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated = '1' THEN
        Tapped_Delay_out1(0) <= Spike;
        Tapped_Delay_out1(11999 DOWNTO 1) <= Tapped_Delay_out1(11998 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Tapped_Delay_process;


  Out1_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Tapped_Delay_out1_last_value <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_gated = '1' THEN
        Tapped_Delay_out1_last_value <= Tapped_Delay_out1_bypass;
      END IF;
    END IF;
  END PROCESS Out1_bypass_process;


  
  Tapped_Delay_out1_bypass <= Tapped_Delay_out1_last_value WHEN Enable_out2 = '0' ELSE
      Tapped_Delay_out1;

  Out1 <= Tapped_Delay_out1_bypass;

END rtl;

