-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\GABA_Synapse.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: GABA_Synapse
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/I_A/GABA_Synapse
-- Hierarchy Level: 2
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY GABA_Synapse IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Spike_Weight1                     :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        s_gaba_out                        :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En8
        );
END GABA_Synapse;


ARCHITECTURE rtl OF GABA_Synapse IS

  -- Signals
  SIGNAL Spike_Weight1_signed             : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Add1_out1                        : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL s_trace1_out1                    : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Decay_Gain_mul_temp              : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_out1                  : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Add1_add_cast                    : signed(24 DOWNTO 0);  -- sfix25_En8
  SIGNAL Add1_add_cast_1                  : signed(24 DOWNTO 0);  -- sfix25_En8
  SIGNAL Add1_add_temp                    : signed(24 DOWNTO 0);  -- sfix25_En8

BEGIN
  Spike_Weight1_signed <= signed(Spike_Weight1);

  s_trace1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      s_trace1_out1 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        s_trace1_out1 <= Add1_out1;
      END IF;
    END IF;
  END PROCESS s_trace1_process;


  Decay_Gain_mul_temp <= to_signed(16#0FEB90#, 24) * s_trace1_out1;
  
  Decay_Gain_out1 <= X"7FFFFF" WHEN (Decay_Gain_mul_temp(47) = '0') AND (Decay_Gain_mul_temp(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp(47) = '1') AND (Decay_Gain_mul_temp(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp(43 DOWNTO 20);

  Add1_add_cast <= resize(Decay_Gain_out1, 25);
  Add1_add_cast_1 <= resize(Spike_Weight1_signed, 25);
  Add1_add_temp <= Add1_add_cast + Add1_add_cast_1;
  
  Add1_out1 <= X"7FFFFF" WHEN (Add1_add_temp(24) = '0') AND (Add1_add_temp(23) /= '0') ELSE
      X"800000" WHEN (Add1_add_temp(24) = '1') AND (Add1_add_temp(23) /= '1') ELSE
      Add1_add_temp(23 DOWNTO 0);

  s_gaba_out <= std_logic_vector(Add1_out1);

END rtl;

