-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\GABA_Synapse_block1.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: GABA_Synapse_block1
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/PE_A/GABA_Synapse
-- Hierarchy Level: 2
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MMN_Core_Chip_pkg.ALL;

ENTITY GABA_Synapse_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Spike_Weight1                     :   IN    vector_of_std_logic_vector24(0 TO 9);  -- sfix24_En8 [10]
        s_gaba_out                        :   OUT   vector_of_std_logic_vector24(0 TO 9)  -- sfix24_En8 [10]
        );
END GABA_Synapse_block1;


ARCHITECTURE rtl OF GABA_Synapse_block1 IS

  -- Signals
  SIGNAL Spike_Weight1_signed             : vector_of_signed24(0 TO 9);  -- sfix24_En8 [10]
  SIGNAL Add1_out1                        : vector_of_signed24(0 TO 9);  -- sfix24_En8 [10]
  SIGNAL s_trace1_out1                    : vector_of_signed24(0 TO 9);  -- sfix24_En8 [10]
  SIGNAL Decay_Gain_mul_temp              : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_1            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_2            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_3            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_4            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_5            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_6            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_7            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_8            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_mul_temp_9            : signed(47 DOWNTO 0);  -- sfix48_En28
  SIGNAL Decay_Gain_out1                  : vector_of_signed24(0 TO 9);  -- sfix24_En8 [10]
  SIGNAL Add1_add_cast                    : vector_of_signed25(0 TO 9);  -- sfix25_En8 [10]
  SIGNAL Add1_add_cast_1                  : vector_of_signed25(0 TO 9);  -- sfix25_En8 [10]
  SIGNAL Add1_add_temp                    : vector_of_signed25(0 TO 9);  -- sfix25_En8 [10]

BEGIN
  outputgen1: FOR k IN 0 TO 9 GENERATE
    Spike_Weight1_signed(k) <= signed(Spike_Weight1(k));
  END GENERATE;

  s_trace1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      s_trace1_out1 <= (OTHERS => to_signed(16#000000#, 24));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        s_trace1_out1 <= Add1_out1;
      END IF;
    END IF;
  END PROCESS s_trace1_process;


  Decay_Gain_mul_temp <= to_signed(16#0FEB90#, 24) * s_trace1_out1(0);
  
  Decay_Gain_out1(0) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp(47) = '0') AND (Decay_Gain_mul_temp(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp(47) = '1') AND (Decay_Gain_mul_temp(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp(43 DOWNTO 20);
  Decay_Gain_mul_temp_1 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(1);
  
  Decay_Gain_out1(1) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_1(47) = '0') AND (Decay_Gain_mul_temp_1(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_1(47) = '1') AND (Decay_Gain_mul_temp_1(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_1(43 DOWNTO 20);
  Decay_Gain_mul_temp_2 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(2);
  
  Decay_Gain_out1(2) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_2(47) = '0') AND (Decay_Gain_mul_temp_2(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_2(47) = '1') AND (Decay_Gain_mul_temp_2(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_2(43 DOWNTO 20);
  Decay_Gain_mul_temp_3 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(3);
  
  Decay_Gain_out1(3) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_3(47) = '0') AND (Decay_Gain_mul_temp_3(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_3(47) = '1') AND (Decay_Gain_mul_temp_3(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_3(43 DOWNTO 20);
  Decay_Gain_mul_temp_4 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(4);
  
  Decay_Gain_out1(4) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_4(47) = '0') AND (Decay_Gain_mul_temp_4(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_4(47) = '1') AND (Decay_Gain_mul_temp_4(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_4(43 DOWNTO 20);
  Decay_Gain_mul_temp_5 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(5);
  
  Decay_Gain_out1(5) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_5(47) = '0') AND (Decay_Gain_mul_temp_5(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_5(47) = '1') AND (Decay_Gain_mul_temp_5(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_5(43 DOWNTO 20);
  Decay_Gain_mul_temp_6 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(6);
  
  Decay_Gain_out1(6) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_6(47) = '0') AND (Decay_Gain_mul_temp_6(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_6(47) = '1') AND (Decay_Gain_mul_temp_6(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_6(43 DOWNTO 20);
  Decay_Gain_mul_temp_7 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(7);
  
  Decay_Gain_out1(7) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_7(47) = '0') AND (Decay_Gain_mul_temp_7(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_7(47) = '1') AND (Decay_Gain_mul_temp_7(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_7(43 DOWNTO 20);
  Decay_Gain_mul_temp_8 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(8);
  
  Decay_Gain_out1(8) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_8(47) = '0') AND (Decay_Gain_mul_temp_8(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_8(47) = '1') AND (Decay_Gain_mul_temp_8(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_8(43 DOWNTO 20);
  Decay_Gain_mul_temp_9 <= to_signed(16#0FEB90#, 24) * s_trace1_out1(9);
  
  Decay_Gain_out1(9) <= X"7FFFFF" WHEN (Decay_Gain_mul_temp_9(47) = '0') AND (Decay_Gain_mul_temp_9(46 DOWNTO 43) /= "0000") ELSE
      X"800000" WHEN (Decay_Gain_mul_temp_9(47) = '1') AND (Decay_Gain_mul_temp_9(46 DOWNTO 43) /= "1111") ELSE
      Decay_Gain_mul_temp_9(43 DOWNTO 20);


  Add1_out1_gen: FOR t_0 IN 0 TO 9 GENERATE
    Add1_add_cast(t_0) <= resize(Decay_Gain_out1(t_0), 25);
    Add1_add_cast_1(t_0) <= resize(Spike_Weight1_signed(t_0), 25);
    Add1_add_temp(t_0) <= Add1_add_cast(t_0) + Add1_add_cast_1(t_0);
    
    Add1_out1(t_0) <= X"7FFFFF" WHEN (Add1_add_temp(t_0)(24) = '0') AND (Add1_add_temp(t_0)(23) /= '0') ELSE
        X"800000" WHEN (Add1_add_temp(t_0)(24) = '1') AND (Add1_add_temp(t_0)(23) /= '1') ELSE
        Add1_add_temp(t_0)(23 DOWNTO 0);
  END GENERATE Add1_out1_gen;


  outputgen: FOR k IN 0 TO 9 GENERATE
    s_gaba_out(k) <= std_logic_vector(Add1_out1(k));
  END GENERATE;

END rtl;

