-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\LIF_Neuron_Conductance_block.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LIF_Neuron_Conductance_block
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/Mem_A/LIF_Neuron_Conductance
-- Hierarchy Level: 2
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY LIF_Neuron_Conductance_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        s_ampa                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        s_gaba                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        I_ext                             :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        Spike                             :   OUT   std_logic
        );
END LIF_Neuron_Conductance_block;


ARCHITECTURE rtl OF LIF_Neuron_Conductance_block IS

  -- Component Declarations
  COMPONENT Detect_Rise_Positive
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          U                               :   IN    std_logic;
          Y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Detect_Rise_Positive
    USE ENTITY work.Detect_Rise_Positive(rtl);

  -- Signals
  SIGNAL Constant3_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant4_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant7_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL s_ampa_signed                    : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Constant1_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL s_gaba_signed                    : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Constant2_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL I_ext_signed                     : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Constant_out1                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant5_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant6_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem                            : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Subtract_sub_cast                : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract_sub_cast_1              : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract_sub_temp                : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract_out1                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Leakage_Gain_mul_temp            : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_out1                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Subtract2_sub_cast               : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract2_sub_cast_1             : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract2_sub_temp               : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract2_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Product1_mul_temp                : signed(55 DOWNTO 0);  -- sfix56_En16
  SIGNAL Product1_out1                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Gain1_mul_temp                   : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL I_gaba                           : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Subtract1_sub_cast               : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract1_sub_cast_1             : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract1_sub_temp               : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Subtract1_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Product_mul_temp                 : signed(55 DOWNTO 0);  -- sfix56_En16
  SIGNAL Product_out1                     : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Gain_mul_temp                    : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL I_ampa                           : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum1_stage2_add_cast             : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum1_stage2_add_cast_1           : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum1_stage2_add_temp             : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum1_stage2_cast                 : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum1_op_stage1                   : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum1_stage3_add_cast             : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum1_stage3_add_cast_1           : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum1_stage3_add_cast_2           : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum1_stage3_add_cast_3           : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum1_stage3_add_temp             : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum1_out1                        : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Current_Gain_mul_temp            : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_out1                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_stage2_add_cast              : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum_stage2_add_cast_1            : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum_stage2_add_temp              : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum_stage2_cast                  : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_op_stage1                    : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum_stage3_add_cast              : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_stage3_add_cast_1            : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum_stage3_add_cast_2            : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum_stage3_add_temp              : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Sum_out1                         : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Detect_Rise_Positive_Y           : std_logic;
  SIGNAL Switch_out1                      : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1                  : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Switch2_out1                     : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Switch1_out1                     : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Refractory_Timer_out1            : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Add_sub_cast                     : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Add_sub_cast_1                   : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Add_sub_temp                     : signed(32 DOWNTO 0);  -- sfix33_En8
  SIGNAL Add_out1                         : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1                  : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Relational_Operator1_out1        : std_logic;
  SIGNAL switch_compare_1_2               : std_logic;
  SIGNAL Switch3_out1                     : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1         : std_logic;

BEGIN
  u_Detect_Rise_Positive : Detect_Rise_Positive
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              U => Relational_Operator_out1,
              Y => Detect_Rise_Positive_Y
              );

  Constant3_out1 <= to_signed(256, 32);

  Constant4_out1 <= to_signed(1024000, 32);

  Constant7_out1 <= to_signed(0, 32);

  s_ampa_signed <= signed(s_ampa);

  Constant1_out1 <= to_signed(0, 32);

  s_gaba_signed <= signed(s_gaba);

  Constant2_out1 <= to_signed(-20480, 32);

  I_ext_signed <= signed(I_ext);

  Constant_out1 <= to_signed(-16640, 32);

  Constant5_out1 <= to_signed(-16640, 32);

  Constant6_out1 <= to_signed(-15360, 32);

  Subtract_sub_cast <= resize(Constant_out1, 33);
  Subtract_sub_cast_1 <= resize(V_mem, 33);
  Subtract_sub_temp <= Subtract_sub_cast - Subtract_sub_cast_1;
  
  Subtract_out1 <= X"7FFFFFFF" WHEN (Subtract_sub_temp(32) = '0') AND (Subtract_sub_temp(31) /= '0') ELSE
      X"80000000" WHEN (Subtract_sub_temp(32) = '1') AND (Subtract_sub_temp(31) /= '1') ELSE
      Subtract_sub_temp(31 DOWNTO 0);

  Leakage_Gain_mul_temp <= to_signed(16#000A3D#, 24) * Subtract_out1;
  
  Leakage_Gain_out1 <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp(55) = '0') AND (Leakage_Gain_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp(55) = '1') AND (Leakage_Gain_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp(51 DOWNTO 20);

  Subtract2_sub_cast <= resize(Constant2_out1, 33);
  Subtract2_sub_cast_1 <= resize(V_mem, 33);
  Subtract2_sub_temp <= Subtract2_sub_cast - Subtract2_sub_cast_1;
  
  Subtract2_out1 <= X"7FFFFFFF" WHEN (Subtract2_sub_temp(32) = '0') AND (Subtract2_sub_temp(31) /= '0') ELSE
      X"80000000" WHEN (Subtract2_sub_temp(32) = '1') AND (Subtract2_sub_temp(31) /= '1') ELSE
      Subtract2_sub_temp(31 DOWNTO 0);

  Product1_mul_temp <= s_gaba_signed * Subtract2_out1;
  
  Product1_out1 <= X"7FFFFFFF" WHEN (Product1_mul_temp(55) = '0') AND (Product1_mul_temp(54 DOWNTO 39) /= X"0000") ELSE
      X"80000000" WHEN (Product1_mul_temp(55) = '1') AND (Product1_mul_temp(54 DOWNTO 39) /= X"FFFF") ELSE
      Product1_mul_temp(39 DOWNTO 8);

  Gain1_mul_temp <= to_signed(16#001EB8#, 24) * Product1_out1;
  
  I_gaba <= X"7FFFFFFF" WHEN (Gain1_mul_temp(55) = '0') AND (Gain1_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp(55) = '1') AND (Gain1_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp(51 DOWNTO 20);

  Subtract1_sub_cast <= resize(Constant1_out1, 33);
  Subtract1_sub_cast_1 <= resize(V_mem, 33);
  Subtract1_sub_temp <= Subtract1_sub_cast - Subtract1_sub_cast_1;
  
  Subtract1_out1 <= X"7FFFFFFF" WHEN (Subtract1_sub_temp(32) = '0') AND (Subtract1_sub_temp(31) /= '0') ELSE
      X"80000000" WHEN (Subtract1_sub_temp(32) = '1') AND (Subtract1_sub_temp(31) /= '1') ELSE
      Subtract1_sub_temp(31 DOWNTO 0);

  Product_mul_temp <= s_ampa_signed * Subtract1_out1;
  
  Product_out1 <= X"7FFFFFFF" WHEN (Product_mul_temp(55) = '0') AND (Product_mul_temp(54 DOWNTO 39) /= X"0000") ELSE
      X"80000000" WHEN (Product_mul_temp(55) = '1') AND (Product_mul_temp(54 DOWNTO 39) /= X"FFFF") ELSE
      Product_mul_temp(39 DOWNTO 8);

  Gain_mul_temp <= to_signed(16#013333#, 24) * Product_out1;
  
  I_ampa <= X"7FFFFFFF" WHEN (Gain_mul_temp(55) = '0') AND (Gain_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp(55) = '1') AND (Gain_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp(51 DOWNTO 20);

  Sum1_stage2_add_cast <= resize(I_ampa, 33);
  Sum1_stage2_add_cast_1 <= resize(I_gaba, 33);
  Sum1_stage2_add_temp <= Sum1_stage2_add_cast + Sum1_stage2_add_cast_1;
  
  Sum1_stage2_cast <= X"7FFFFFFF" WHEN (Sum1_stage2_add_temp(32) = '0') AND (Sum1_stage2_add_temp(31) /= '0') ELSE
      X"80000000" WHEN (Sum1_stage2_add_temp(32) = '1') AND (Sum1_stage2_add_temp(31) /= '1') ELSE
      Sum1_stage2_add_temp(31 DOWNTO 0);
  Sum1_op_stage1 <= resize(Sum1_stage2_cast, 33);

  
  Sum1_stage3_add_cast <= X"7FFFFFFF" WHEN (Sum1_op_stage1(32) = '0') AND (Sum1_op_stage1(31) /= '0') ELSE
      X"80000000" WHEN (Sum1_op_stage1(32) = '1') AND (Sum1_op_stage1(31) /= '1') ELSE
      Sum1_op_stage1(31 DOWNTO 0);
  Sum1_stage3_add_cast_1 <= resize(Sum1_stage3_add_cast, 33);
  Sum1_stage3_add_cast_2 <= resize(I_ext_signed, 32);
  Sum1_stage3_add_cast_3 <= resize(Sum1_stage3_add_cast_2, 33);
  Sum1_stage3_add_temp <= Sum1_stage3_add_cast_1 + Sum1_stage3_add_cast_3;
  
  Sum1_out1 <= X"7FFFFFFF" WHEN (Sum1_stage3_add_temp(32) = '0') AND (Sum1_stage3_add_temp(31) /= '0') ELSE
      X"80000000" WHEN (Sum1_stage3_add_temp(32) = '1') AND (Sum1_stage3_add_temp(31) /= '1') ELSE
      Sum1_stage3_add_temp(31 DOWNTO 0);

  Current_Gain_mul_temp <= to_signed(16#000A3D#, 24) * Sum1_out1;
  
  Current_Gain_out1 <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp(55) = '0') AND (Current_Gain_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp(55) = '1') AND (Current_Gain_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp(51 DOWNTO 20);

  Sum_stage2_add_cast <= resize(Current_Gain_out1, 33);
  Sum_stage2_add_cast_1 <= resize(V_mem, 33);
  Sum_stage2_add_temp <= Sum_stage2_add_cast + Sum_stage2_add_cast_1;
  
  Sum_stage2_cast <= X"7FFFFFFF" WHEN (Sum_stage2_add_temp(32) = '0') AND (Sum_stage2_add_temp(31) /= '0') ELSE
      X"80000000" WHEN (Sum_stage2_add_temp(32) = '1') AND (Sum_stage2_add_temp(31) /= '1') ELSE
      Sum_stage2_add_temp(31 DOWNTO 0);
  Sum_op_stage1 <= resize(Sum_stage2_cast, 33);

  
  Sum_stage3_add_cast <= X"7FFFFFFF" WHEN (Sum_op_stage1(32) = '0') AND (Sum_op_stage1(31) /= '0') ELSE
      X"80000000" WHEN (Sum_op_stage1(32) = '1') AND (Sum_op_stage1(31) /= '1') ELSE
      Sum_op_stage1(31 DOWNTO 0);
  Sum_stage3_add_cast_1 <= resize(Sum_stage3_add_cast, 33);
  Sum_stage3_add_cast_2 <= resize(Leakage_Gain_out1, 33);
  Sum_stage3_add_temp <= Sum_stage3_add_cast_1 + Sum_stage3_add_cast_2;
  
  Sum_out1 <= X"7FFFFFFF" WHEN (Sum_stage3_add_temp(32) = '0') AND (Sum_stage3_add_temp(31) /= '0') ELSE
      X"80000000" WHEN (Sum_stage3_add_temp(32) = '1') AND (Sum_stage3_add_temp(31) /= '1') ELSE
      Sum_stage3_add_temp(31 DOWNTO 0);

  
  Switch_out1 <= Sum_out1 WHEN Detect_Rise_Positive_Y = '0' ELSE
      Constant_out1;

  
  switch_compare_1 <= '1' WHEN Unit_Delay_out1 > '0' ELSE
      '0';

  
  Switch2_out1 <= Switch_out1 WHEN switch_compare_1 = '0' ELSE
      Constant5_out1;

  Refractory_Timer_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Refractory_Timer_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Refractory_Timer_out1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Refractory_Timer_process;


  Add_sub_cast <= resize(Refractory_Timer_out1, 33);
  Add_sub_cast_1 <= resize(Constant3_out1, 33);
  Add_sub_temp <= Add_sub_cast - Add_sub_cast_1;
  
  Add_out1 <= X"7FFFFFFF" WHEN (Add_sub_temp(32) = '0') AND (Add_sub_temp(31) /= '0') ELSE
      X"80000000" WHEN (Add_sub_temp(32) = '1') AND (Add_sub_temp(31) /= '1') ELSE
      Add_sub_temp(31 DOWNTO 0);

  
  Saturation_out1 <= to_signed(1024000, 32) WHEN Add_out1 > to_signed(1024000, 32) ELSE
      to_signed(0, 32) WHEN Add_out1 < to_signed(0, 32) ELSE
      Add_out1;

  
  switch_compare_1_1 <= '1' WHEN Detect_Rise_Positive_Y > '0' ELSE
      '0';

  
  Switch1_out1 <= Saturation_out1 WHEN switch_compare_1_1 = '0' ELSE
      Constant4_out1;

  
  Relational_Operator1_out1 <= '1' WHEN Switch1_out1 > Constant7_out1 ELSE
      '0';

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Relational_Operator1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  
  switch_compare_1_2 <= '1' WHEN Unit_Delay_out1 > '0' ELSE
      '0';

  
  Switch3_out1 <= Switch2_out1 WHEN switch_compare_1_2 = '0' ELSE
      V_mem;

  V_mem_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      V_mem <= to_signed(-16640, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        V_mem <= Switch3_out1;
      END IF;
    END IF;
  END PROCESS V_mem_1_process;


  
  Relational_Operator_out1 <= '1' WHEN V_mem >= Constant6_out1 ELSE
      '0';

  Spike <= Detect_Rise_Positive_Y;

END rtl;

