-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\LIF_Neuron_Conductance.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LIF_Neuron_Conductance
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/I_A/LIF_Neuron_Conductance
-- Hierarchy Level: 2
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MMN_Core_Chip_pkg.ALL;

ENTITY LIF_Neuron_Conductance IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        s_ampa                            :   IN    vector_of_std_logic_vector24(0 TO 9);  -- sfix24_En8 [10]
        s_gaba                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        I_ext                             :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        Spike                             :   OUT   std_logic_vector(9 DOWNTO 0)  -- boolean [10]
        );
END LIF_Neuron_Conductance;


ARCHITECTURE rtl OF LIF_Neuron_Conductance IS

  -- Signals
  SIGNAL Constant3_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant4_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant7_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL s_ampa_signed                    : vector_of_signed24(0 TO 9);  -- sfix24_En8 [10]
  SIGNAL Constant1_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL s_gaba_signed                    : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Constant2_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL I_ext_signed                     : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Constant_out1                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant5_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Constant6_out1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem                            : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL V_mem_9                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1                         : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Sum_out1_9                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1         : std_logic_vector(9 DOWNTO 0);  -- boolean [10]
  SIGNAL Relational_Operator_out1_9       : std_logic;
  SIGNAL Switch_out1_9                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1                  : std_logic_vector(9 DOWNTO 0);  -- boolean [10]
  SIGNAL Unit_Delay_out1_9                : std_logic;
  SIGNAL switch_compare_10                : std_logic;
  SIGNAL Switch2_out1_9                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_9_1              : std_logic;
  SIGNAL switch_compare_10_1              : std_logic;
  SIGNAL Switch3_out1_9                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_8                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_8                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_8       : std_logic;
  SIGNAL Switch_out1_8                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_8                : std_logic;
  SIGNAL switch_compare_9                 : std_logic;
  SIGNAL Switch2_out1_8                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_8_1              : std_logic;
  SIGNAL switch_compare_9_1               : std_logic;
  SIGNAL Switch3_out1_8                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_7                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_7                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_7       : std_logic;
  SIGNAL Switch_out1_7                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_7                : std_logic;
  SIGNAL switch_compare_8                 : std_logic;
  SIGNAL Switch2_out1_7                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_7_1              : std_logic;
  SIGNAL switch_compare_8_1               : std_logic;
  SIGNAL Switch3_out1_7                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_6                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_6                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_6       : std_logic;
  SIGNAL Switch_out1_6                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_6                : std_logic;
  SIGNAL switch_compare_7                 : std_logic;
  SIGNAL Switch2_out1_6                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_6_1              : std_logic;
  SIGNAL switch_compare_7_1               : std_logic;
  SIGNAL Switch3_out1_6                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_5                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_5                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_5       : std_logic;
  SIGNAL Switch_out1_5                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_5                : std_logic;
  SIGNAL switch_compare_6                 : std_logic;
  SIGNAL Switch2_out1_5                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_5_1              : std_logic;
  SIGNAL switch_compare_6_1               : std_logic;
  SIGNAL Switch3_out1_5                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_4                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_4                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_4       : std_logic;
  SIGNAL Switch_out1_4                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_4                : std_logic;
  SIGNAL switch_compare_5                 : std_logic;
  SIGNAL Switch2_out1_4                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_4_1              : std_logic;
  SIGNAL switch_compare_5_1               : std_logic;
  SIGNAL Switch3_out1_4                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_3                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_3                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_3       : std_logic;
  SIGNAL Switch_out1_3                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_3                : std_logic;
  SIGNAL switch_compare_4                 : std_logic;
  SIGNAL Switch2_out1_3                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_3_1              : std_logic;
  SIGNAL switch_compare_4_1               : std_logic;
  SIGNAL Switch3_out1_3                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_2                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_2                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_2       : std_logic;
  SIGNAL Switch_out1_2                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_2                : std_logic;
  SIGNAL switch_compare_3                 : std_logic;
  SIGNAL Switch2_out1_2                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_2_1              : std_logic;
  SIGNAL switch_compare_3_1               : std_logic;
  SIGNAL Switch3_out1_2                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_1                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum_out1_1                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_1       : std_logic;
  SIGNAL Switch_out1_1                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_1                : std_logic;
  SIGNAL switch_compare_2                 : std_logic;
  SIGNAL Switch2_out1_1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_1_1              : std_logic;
  SIGNAL switch_compare_2_1               : std_logic;
  SIGNAL Switch3_out1_1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL V_mem_0                          : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Subtract_sub_cast                : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract_sub_cast_1              : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract_sub_temp                : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract_out1                    : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Leakage_Gain_mul_temp            : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_1          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_2          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_3          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_4          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_5          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_6          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_7          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_8          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_mul_temp_9          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Leakage_Gain_out1                : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Subtract2_sub_cast               : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract2_sub_cast_1             : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract2_sub_temp               : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract2_out1                   : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Product1_mul_temp                : vector_of_signed56(0 TO 9);  -- sfix56_En16 [10]
  SIGNAL Product1_out1                    : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Gain1_mul_temp                   : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_1                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_2                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_3                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_4                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_5                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_6                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_7                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_8                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain1_mul_temp_9                 : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL I_gaba                           : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Subtract1_sub_cast               : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract1_sub_cast_1             : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract1_sub_temp               : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Subtract1_out1                   : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Product_mul_temp                 : vector_of_signed56(0 TO 9);  -- sfix56_En16 [10]
  SIGNAL Product_out1                     : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Gain_mul_temp                    : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_1                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_2                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_3                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_4                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_5                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_6                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_7                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_8                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Gain_mul_temp_9                  : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL I_ampa                           : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Sum1_stage2_add_cast             : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum1_stage2_add_cast_1           : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum1_stage2_add_temp             : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum1_stage2_cast                 : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Sum1_op_stage1                   : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum1_stage3_v                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Sum1_stage3_add_cast             : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Sum1_stage3_add_cast_1           : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum1_stage3_add_cast_2           : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum1_stage3_add_temp             : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum1_out1                        : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Current_Gain_mul_temp            : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_1          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_2          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_3          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_4          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_5          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_6          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_7          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_8          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_mul_temp_9          : signed(55 DOWNTO 0);  -- sfix56_En28
  SIGNAL Current_Gain_out1                : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Sum_stage2_add_cast              : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum_stage2_add_cast_1            : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum_stage2_add_temp              : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum_stage2_cast                  : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Sum_op_stage1                    : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum_stage3_add_cast              : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Sum_stage3_add_cast_1            : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum_stage3_add_cast_2            : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum_stage3_add_temp              : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Sum_out1_0                       : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_0       : std_logic;
  SIGNAL Switch_out1_0                    : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Unit_Delay_out1_0                : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Switch2_out1_0                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1                  : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Saturation_out1_9                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_9_1     : std_logic;
  SIGNAL switch_compare_10_2              : std_logic;
  SIGNAL Switch1_out1_9                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_8                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_8_1     : std_logic;
  SIGNAL switch_compare_9_2               : std_logic;
  SIGNAL Switch1_out1_8                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_7                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_7_1     : std_logic;
  SIGNAL switch_compare_8_2               : std_logic;
  SIGNAL Switch1_out1_7                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_6                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_6_1     : std_logic;
  SIGNAL switch_compare_7_2               : std_logic;
  SIGNAL Switch1_out1_6                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_5                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_5_1     : std_logic;
  SIGNAL switch_compare_6_2               : std_logic;
  SIGNAL Switch1_out1_5                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_4                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_4_1     : std_logic;
  SIGNAL switch_compare_5_2               : std_logic;
  SIGNAL Switch1_out1_4                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_3                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_3_1     : std_logic;
  SIGNAL switch_compare_4_2               : std_logic;
  SIGNAL Switch1_out1_3                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_2                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_2_1     : std_logic;
  SIGNAL switch_compare_3_2               : std_logic;
  SIGNAL Switch1_out1_2                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Saturation_out1_1                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_1_1     : std_logic;
  SIGNAL switch_compare_2_2               : std_logic;
  SIGNAL Switch1_out1_1                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Switch1_out1                     : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Refractory_Timer_out1            : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Add_sub_cast                     : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Add_sub_cast_1                   : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Add_sub_temp                     : vector_of_signed33(0 TO 9);  -- sfix33_En8 [10]
  SIGNAL Add_out1                         : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]
  SIGNAL Saturation_out1_0                : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator_out1_0_1     : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Switch1_out1_0                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Relational_Operator1_out1        : std_logic_vector(9 DOWNTO 0);  -- boolean [10]
  SIGNAL Unit_Delay_out1_0_1              : std_logic;
  SIGNAL switch_compare_1_2               : std_logic;
  SIGNAL Switch3_out1_0                   : signed(31 DOWNTO 0);  -- sfix32_En8
  SIGNAL Switch3_out1                     : vector_of_signed32(0 TO 9);  -- sfix32_En8 [10]

BEGIN
  Constant3_out1 <= to_signed(256, 32);

  Constant4_out1 <= to_signed(10240, 32);

  Constant7_out1 <= to_signed(0, 32);

  outputgen: FOR k IN 0 TO 9 GENERATE
    s_ampa_signed(k) <= signed(s_ampa(k));
  END GENERATE;

  Constant1_out1 <= to_signed(0, 32);

  s_gaba_signed <= signed(s_gaba);

  Constant2_out1 <= to_signed(-20480, 32);

  I_ext_signed <= signed(I_ext);

  Constant_out1 <= to_signed(-16640, 32);

  Constant5_out1 <= to_signed(-16640, 32);

  Constant6_out1 <= to_signed(-15360, 32);

  V_mem_9 <= V_mem(9);

  Sum_out1_9 <= Sum_out1(9);

  Relational_Operator_out1_9 <= Relational_Operator_out1(9);

  
  Switch_out1_9 <= Sum_out1_9 WHEN Relational_Operator_out1_9 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_9 <= Unit_Delay_out1(9);

  
  switch_compare_10 <= '1' WHEN Unit_Delay_out1_9 > '0' ELSE
      '0';

  
  Switch2_out1_9 <= Switch_out1_9 WHEN switch_compare_10 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_9_1 <= Unit_Delay_out1(9);

  
  switch_compare_10_1 <= '1' WHEN Unit_Delay_out1_9_1 > '0' ELSE
      '0';

  
  Switch3_out1_9 <= Switch2_out1_9 WHEN switch_compare_10_1 = '0' ELSE
      V_mem_9;

  V_mem_8 <= V_mem(8);

  Sum_out1_8 <= Sum_out1(8);

  Relational_Operator_out1_8 <= Relational_Operator_out1(8);

  
  Switch_out1_8 <= Sum_out1_8 WHEN Relational_Operator_out1_8 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_8 <= Unit_Delay_out1(8);

  
  switch_compare_9 <= '1' WHEN Unit_Delay_out1_8 > '0' ELSE
      '0';

  
  Switch2_out1_8 <= Switch_out1_8 WHEN switch_compare_9 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_8_1 <= Unit_Delay_out1(8);

  
  switch_compare_9_1 <= '1' WHEN Unit_Delay_out1_8_1 > '0' ELSE
      '0';

  
  Switch3_out1_8 <= Switch2_out1_8 WHEN switch_compare_9_1 = '0' ELSE
      V_mem_8;

  V_mem_7 <= V_mem(7);

  Sum_out1_7 <= Sum_out1(7);

  Relational_Operator_out1_7 <= Relational_Operator_out1(7);

  
  Switch_out1_7 <= Sum_out1_7 WHEN Relational_Operator_out1_7 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_7 <= Unit_Delay_out1(7);

  
  switch_compare_8 <= '1' WHEN Unit_Delay_out1_7 > '0' ELSE
      '0';

  
  Switch2_out1_7 <= Switch_out1_7 WHEN switch_compare_8 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_7_1 <= Unit_Delay_out1(7);

  
  switch_compare_8_1 <= '1' WHEN Unit_Delay_out1_7_1 > '0' ELSE
      '0';

  
  Switch3_out1_7 <= Switch2_out1_7 WHEN switch_compare_8_1 = '0' ELSE
      V_mem_7;

  V_mem_6 <= V_mem(6);

  Sum_out1_6 <= Sum_out1(6);

  Relational_Operator_out1_6 <= Relational_Operator_out1(6);

  
  Switch_out1_6 <= Sum_out1_6 WHEN Relational_Operator_out1_6 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_6 <= Unit_Delay_out1(6);

  
  switch_compare_7 <= '1' WHEN Unit_Delay_out1_6 > '0' ELSE
      '0';

  
  Switch2_out1_6 <= Switch_out1_6 WHEN switch_compare_7 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_6_1 <= Unit_Delay_out1(6);

  
  switch_compare_7_1 <= '1' WHEN Unit_Delay_out1_6_1 > '0' ELSE
      '0';

  
  Switch3_out1_6 <= Switch2_out1_6 WHEN switch_compare_7_1 = '0' ELSE
      V_mem_6;

  V_mem_5 <= V_mem(5);

  Sum_out1_5 <= Sum_out1(5);

  Relational_Operator_out1_5 <= Relational_Operator_out1(5);

  
  Switch_out1_5 <= Sum_out1_5 WHEN Relational_Operator_out1_5 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_5 <= Unit_Delay_out1(5);

  
  switch_compare_6 <= '1' WHEN Unit_Delay_out1_5 > '0' ELSE
      '0';

  
  Switch2_out1_5 <= Switch_out1_5 WHEN switch_compare_6 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_5_1 <= Unit_Delay_out1(5);

  
  switch_compare_6_1 <= '1' WHEN Unit_Delay_out1_5_1 > '0' ELSE
      '0';

  
  Switch3_out1_5 <= Switch2_out1_5 WHEN switch_compare_6_1 = '0' ELSE
      V_mem_5;

  V_mem_4 <= V_mem(4);

  Sum_out1_4 <= Sum_out1(4);

  Relational_Operator_out1_4 <= Relational_Operator_out1(4);

  
  Switch_out1_4 <= Sum_out1_4 WHEN Relational_Operator_out1_4 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_4 <= Unit_Delay_out1(4);

  
  switch_compare_5 <= '1' WHEN Unit_Delay_out1_4 > '0' ELSE
      '0';

  
  Switch2_out1_4 <= Switch_out1_4 WHEN switch_compare_5 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_4_1 <= Unit_Delay_out1(4);

  
  switch_compare_5_1 <= '1' WHEN Unit_Delay_out1_4_1 > '0' ELSE
      '0';

  
  Switch3_out1_4 <= Switch2_out1_4 WHEN switch_compare_5_1 = '0' ELSE
      V_mem_4;

  V_mem_3 <= V_mem(3);

  Sum_out1_3 <= Sum_out1(3);

  Relational_Operator_out1_3 <= Relational_Operator_out1(3);

  
  Switch_out1_3 <= Sum_out1_3 WHEN Relational_Operator_out1_3 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_3 <= Unit_Delay_out1(3);

  
  switch_compare_4 <= '1' WHEN Unit_Delay_out1_3 > '0' ELSE
      '0';

  
  Switch2_out1_3 <= Switch_out1_3 WHEN switch_compare_4 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_3_1 <= Unit_Delay_out1(3);

  
  switch_compare_4_1 <= '1' WHEN Unit_Delay_out1_3_1 > '0' ELSE
      '0';

  
  Switch3_out1_3 <= Switch2_out1_3 WHEN switch_compare_4_1 = '0' ELSE
      V_mem_3;

  V_mem_2 <= V_mem(2);

  Sum_out1_2 <= Sum_out1(2);

  Relational_Operator_out1_2 <= Relational_Operator_out1(2);

  
  Switch_out1_2 <= Sum_out1_2 WHEN Relational_Operator_out1_2 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_2 <= Unit_Delay_out1(2);

  
  switch_compare_3 <= '1' WHEN Unit_Delay_out1_2 > '0' ELSE
      '0';

  
  Switch2_out1_2 <= Switch_out1_2 WHEN switch_compare_3 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_2_1 <= Unit_Delay_out1(2);

  
  switch_compare_3_1 <= '1' WHEN Unit_Delay_out1_2_1 > '0' ELSE
      '0';

  
  Switch3_out1_2 <= Switch2_out1_2 WHEN switch_compare_3_1 = '0' ELSE
      V_mem_2;

  V_mem_1 <= V_mem(1);

  Sum_out1_1 <= Sum_out1(1);

  Relational_Operator_out1_1 <= Relational_Operator_out1(1);

  
  Switch_out1_1 <= Sum_out1_1 WHEN Relational_Operator_out1_1 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_1 <= Unit_Delay_out1(1);

  
  switch_compare_2 <= '1' WHEN Unit_Delay_out1_1 > '0' ELSE
      '0';

  
  Switch2_out1_1 <= Switch_out1_1 WHEN switch_compare_2 = '0' ELSE
      Constant5_out1;

  Unit_Delay_out1_1_1 <= Unit_Delay_out1(1);

  
  switch_compare_2_1 <= '1' WHEN Unit_Delay_out1_1_1 > '0' ELSE
      '0';

  
  Switch3_out1_1 <= Switch2_out1_1 WHEN switch_compare_2_1 = '0' ELSE
      V_mem_1;

  V_mem_0 <= V_mem(0);


  Subtract_out1_gen: FOR t_0 IN 0 TO 9 GENERATE
    Subtract_sub_cast(t_0) <= resize(Constant_out1, 33);
    Subtract_sub_cast_1(t_0) <= resize(V_mem(t_0), 33);
    Subtract_sub_temp(t_0) <= Subtract_sub_cast(t_0) - Subtract_sub_cast_1(t_0);
    
    Subtract_out1(t_0) <= X"7FFFFFFF" WHEN (Subtract_sub_temp(t_0)(32) = '0') AND (Subtract_sub_temp(t_0)(31) /= '0') ELSE
        X"80000000" WHEN (Subtract_sub_temp(t_0)(32) = '1') AND (Subtract_sub_temp(t_0)(31) /= '1') ELSE
        Subtract_sub_temp(t_0)(31 DOWNTO 0);
  END GENERATE Subtract_out1_gen;


  Leakage_Gain_mul_temp <= to_signed(16#000A3D#, 24) * Subtract_out1(0);
  
  Leakage_Gain_out1(0) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp(55) = '0') AND (Leakage_Gain_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp(55) = '1') AND (Leakage_Gain_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp(51 DOWNTO 20);
  Leakage_Gain_mul_temp_1 <= to_signed(16#000A3D#, 24) * Subtract_out1(1);
  
  Leakage_Gain_out1(1) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_1(55) = '0') AND (Leakage_Gain_mul_temp_1(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_1(55) = '1') AND (Leakage_Gain_mul_temp_1(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_1(51 DOWNTO 20);
  Leakage_Gain_mul_temp_2 <= to_signed(16#000A3D#, 24) * Subtract_out1(2);
  
  Leakage_Gain_out1(2) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_2(55) = '0') AND (Leakage_Gain_mul_temp_2(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_2(55) = '1') AND (Leakage_Gain_mul_temp_2(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_2(51 DOWNTO 20);
  Leakage_Gain_mul_temp_3 <= to_signed(16#000A3D#, 24) * Subtract_out1(3);
  
  Leakage_Gain_out1(3) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_3(55) = '0') AND (Leakage_Gain_mul_temp_3(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_3(55) = '1') AND (Leakage_Gain_mul_temp_3(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_3(51 DOWNTO 20);
  Leakage_Gain_mul_temp_4 <= to_signed(16#000A3D#, 24) * Subtract_out1(4);
  
  Leakage_Gain_out1(4) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_4(55) = '0') AND (Leakage_Gain_mul_temp_4(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_4(55) = '1') AND (Leakage_Gain_mul_temp_4(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_4(51 DOWNTO 20);
  Leakage_Gain_mul_temp_5 <= to_signed(16#000A3D#, 24) * Subtract_out1(5);
  
  Leakage_Gain_out1(5) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_5(55) = '0') AND (Leakage_Gain_mul_temp_5(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_5(55) = '1') AND (Leakage_Gain_mul_temp_5(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_5(51 DOWNTO 20);
  Leakage_Gain_mul_temp_6 <= to_signed(16#000A3D#, 24) * Subtract_out1(6);
  
  Leakage_Gain_out1(6) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_6(55) = '0') AND (Leakage_Gain_mul_temp_6(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_6(55) = '1') AND (Leakage_Gain_mul_temp_6(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_6(51 DOWNTO 20);
  Leakage_Gain_mul_temp_7 <= to_signed(16#000A3D#, 24) * Subtract_out1(7);
  
  Leakage_Gain_out1(7) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_7(55) = '0') AND (Leakage_Gain_mul_temp_7(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_7(55) = '1') AND (Leakage_Gain_mul_temp_7(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_7(51 DOWNTO 20);
  Leakage_Gain_mul_temp_8 <= to_signed(16#000A3D#, 24) * Subtract_out1(8);
  
  Leakage_Gain_out1(8) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_8(55) = '0') AND (Leakage_Gain_mul_temp_8(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_8(55) = '1') AND (Leakage_Gain_mul_temp_8(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_8(51 DOWNTO 20);
  Leakage_Gain_mul_temp_9 <= to_signed(16#000A3D#, 24) * Subtract_out1(9);
  
  Leakage_Gain_out1(9) <= X"7FFFFFFF" WHEN (Leakage_Gain_mul_temp_9(55) = '0') AND (Leakage_Gain_mul_temp_9(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Leakage_Gain_mul_temp_9(55) = '1') AND (Leakage_Gain_mul_temp_9(54 DOWNTO 51) /= "1111") ELSE
      Leakage_Gain_mul_temp_9(51 DOWNTO 20);


  Subtract2_out1_gen: FOR t_01 IN 0 TO 9 GENERATE
    Subtract2_sub_cast(t_01) <= resize(Constant2_out1, 33);
    Subtract2_sub_cast_1(t_01) <= resize(V_mem(t_01), 33);
    Subtract2_sub_temp(t_01) <= Subtract2_sub_cast(t_01) - Subtract2_sub_cast_1(t_01);
    
    Subtract2_out1(t_01) <= X"7FFFFFFF" WHEN (Subtract2_sub_temp(t_01)(32) = '0') AND (Subtract2_sub_temp(t_01)(31) /= '0') ELSE
        X"80000000" WHEN (Subtract2_sub_temp(t_01)(32) = '1') AND (Subtract2_sub_temp(t_01)(31) /= '1') ELSE
        Subtract2_sub_temp(t_01)(31 DOWNTO 0);
  END GENERATE Subtract2_out1_gen;



  Product1_out1_gen: FOR t_02 IN 0 TO 9 GENERATE
    Product1_mul_temp(t_02) <= s_gaba_signed * Subtract2_out1(t_02);
    
    Product1_out1(t_02) <= X"7FFFFFFF" WHEN (Product1_mul_temp(t_02)(55) = '0') AND (Product1_mul_temp(t_02)(54 DOWNTO 39) /= X"0000") ELSE
        X"80000000" WHEN (Product1_mul_temp(t_02)(55) = '1') AND (Product1_mul_temp(t_02)(54 DOWNTO 39) /= X"FFFF") ELSE
        Product1_mul_temp(t_02)(39 DOWNTO 8);
  END GENERATE Product1_out1_gen;


  Gain1_mul_temp <= to_signed(16#001EB8#, 24) * Product1_out1(0);
  
  I_gaba(0) <= X"7FFFFFFF" WHEN (Gain1_mul_temp(55) = '0') AND (Gain1_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp(55) = '1') AND (Gain1_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp(51 DOWNTO 20);
  Gain1_mul_temp_1 <= to_signed(16#001EB8#, 24) * Product1_out1(1);
  
  I_gaba(1) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_1(55) = '0') AND (Gain1_mul_temp_1(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_1(55) = '1') AND (Gain1_mul_temp_1(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_1(51 DOWNTO 20);
  Gain1_mul_temp_2 <= to_signed(16#001EB8#, 24) * Product1_out1(2);
  
  I_gaba(2) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_2(55) = '0') AND (Gain1_mul_temp_2(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_2(55) = '1') AND (Gain1_mul_temp_2(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_2(51 DOWNTO 20);
  Gain1_mul_temp_3 <= to_signed(16#001EB8#, 24) * Product1_out1(3);
  
  I_gaba(3) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_3(55) = '0') AND (Gain1_mul_temp_3(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_3(55) = '1') AND (Gain1_mul_temp_3(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_3(51 DOWNTO 20);
  Gain1_mul_temp_4 <= to_signed(16#001EB8#, 24) * Product1_out1(4);
  
  I_gaba(4) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_4(55) = '0') AND (Gain1_mul_temp_4(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_4(55) = '1') AND (Gain1_mul_temp_4(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_4(51 DOWNTO 20);
  Gain1_mul_temp_5 <= to_signed(16#001EB8#, 24) * Product1_out1(5);
  
  I_gaba(5) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_5(55) = '0') AND (Gain1_mul_temp_5(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_5(55) = '1') AND (Gain1_mul_temp_5(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_5(51 DOWNTO 20);
  Gain1_mul_temp_6 <= to_signed(16#001EB8#, 24) * Product1_out1(6);
  
  I_gaba(6) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_6(55) = '0') AND (Gain1_mul_temp_6(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_6(55) = '1') AND (Gain1_mul_temp_6(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_6(51 DOWNTO 20);
  Gain1_mul_temp_7 <= to_signed(16#001EB8#, 24) * Product1_out1(7);
  
  I_gaba(7) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_7(55) = '0') AND (Gain1_mul_temp_7(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_7(55) = '1') AND (Gain1_mul_temp_7(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_7(51 DOWNTO 20);
  Gain1_mul_temp_8 <= to_signed(16#001EB8#, 24) * Product1_out1(8);
  
  I_gaba(8) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_8(55) = '0') AND (Gain1_mul_temp_8(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_8(55) = '1') AND (Gain1_mul_temp_8(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_8(51 DOWNTO 20);
  Gain1_mul_temp_9 <= to_signed(16#001EB8#, 24) * Product1_out1(9);
  
  I_gaba(9) <= X"7FFFFFFF" WHEN (Gain1_mul_temp_9(55) = '0') AND (Gain1_mul_temp_9(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain1_mul_temp_9(55) = '1') AND (Gain1_mul_temp_9(54 DOWNTO 51) /= "1111") ELSE
      Gain1_mul_temp_9(51 DOWNTO 20);


  Subtract1_out1_gen: FOR t_03 IN 0 TO 9 GENERATE
    Subtract1_sub_cast(t_03) <= resize(Constant1_out1, 33);
    Subtract1_sub_cast_1(t_03) <= resize(V_mem(t_03), 33);
    Subtract1_sub_temp(t_03) <= Subtract1_sub_cast(t_03) - Subtract1_sub_cast_1(t_03);
    
    Subtract1_out1(t_03) <= X"7FFFFFFF" WHEN (Subtract1_sub_temp(t_03)(32) = '0') AND (Subtract1_sub_temp(t_03)(31) /= '0') ELSE
        X"80000000" WHEN (Subtract1_sub_temp(t_03)(32) = '1') AND (Subtract1_sub_temp(t_03)(31) /= '1') ELSE
        Subtract1_sub_temp(t_03)(31 DOWNTO 0);
  END GENERATE Subtract1_out1_gen;



  Product_out1_gen: FOR t_04 IN 0 TO 9 GENERATE
    Product_mul_temp(t_04) <= s_ampa_signed(t_04) * Subtract1_out1(t_04);
    
    Product_out1(t_04) <= X"7FFFFFFF" WHEN (Product_mul_temp(t_04)(55) = '0') AND (Product_mul_temp(t_04)(54 DOWNTO 39) /= X"0000") ELSE
        X"80000000" WHEN (Product_mul_temp(t_04)(55) = '1') AND (Product_mul_temp(t_04)(54 DOWNTO 39) /= X"FFFF") ELSE
        Product_mul_temp(t_04)(39 DOWNTO 8);
  END GENERATE Product_out1_gen;


  Gain_mul_temp <= to_signed(16#013333#, 24) * Product_out1(0);
  
  I_ampa(0) <= X"7FFFFFFF" WHEN (Gain_mul_temp(55) = '0') AND (Gain_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp(55) = '1') AND (Gain_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp(51 DOWNTO 20);
  Gain_mul_temp_1 <= to_signed(16#013333#, 24) * Product_out1(1);
  
  I_ampa(1) <= X"7FFFFFFF" WHEN (Gain_mul_temp_1(55) = '0') AND (Gain_mul_temp_1(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_1(55) = '1') AND (Gain_mul_temp_1(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_1(51 DOWNTO 20);
  Gain_mul_temp_2 <= to_signed(16#013333#, 24) * Product_out1(2);
  
  I_ampa(2) <= X"7FFFFFFF" WHEN (Gain_mul_temp_2(55) = '0') AND (Gain_mul_temp_2(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_2(55) = '1') AND (Gain_mul_temp_2(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_2(51 DOWNTO 20);
  Gain_mul_temp_3 <= to_signed(16#013333#, 24) * Product_out1(3);
  
  I_ampa(3) <= X"7FFFFFFF" WHEN (Gain_mul_temp_3(55) = '0') AND (Gain_mul_temp_3(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_3(55) = '1') AND (Gain_mul_temp_3(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_3(51 DOWNTO 20);
  Gain_mul_temp_4 <= to_signed(16#013333#, 24) * Product_out1(4);
  
  I_ampa(4) <= X"7FFFFFFF" WHEN (Gain_mul_temp_4(55) = '0') AND (Gain_mul_temp_4(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_4(55) = '1') AND (Gain_mul_temp_4(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_4(51 DOWNTO 20);
  Gain_mul_temp_5 <= to_signed(16#013333#, 24) * Product_out1(5);
  
  I_ampa(5) <= X"7FFFFFFF" WHEN (Gain_mul_temp_5(55) = '0') AND (Gain_mul_temp_5(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_5(55) = '1') AND (Gain_mul_temp_5(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_5(51 DOWNTO 20);
  Gain_mul_temp_6 <= to_signed(16#013333#, 24) * Product_out1(6);
  
  I_ampa(6) <= X"7FFFFFFF" WHEN (Gain_mul_temp_6(55) = '0') AND (Gain_mul_temp_6(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_6(55) = '1') AND (Gain_mul_temp_6(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_6(51 DOWNTO 20);
  Gain_mul_temp_7 <= to_signed(16#013333#, 24) * Product_out1(7);
  
  I_ampa(7) <= X"7FFFFFFF" WHEN (Gain_mul_temp_7(55) = '0') AND (Gain_mul_temp_7(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_7(55) = '1') AND (Gain_mul_temp_7(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_7(51 DOWNTO 20);
  Gain_mul_temp_8 <= to_signed(16#013333#, 24) * Product_out1(8);
  
  I_ampa(8) <= X"7FFFFFFF" WHEN (Gain_mul_temp_8(55) = '0') AND (Gain_mul_temp_8(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_8(55) = '1') AND (Gain_mul_temp_8(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_8(51 DOWNTO 20);
  Gain_mul_temp_9 <= to_signed(16#013333#, 24) * Product_out1(9);
  
  I_ampa(9) <= X"7FFFFFFF" WHEN (Gain_mul_temp_9(55) = '0') AND (Gain_mul_temp_9(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Gain_mul_temp_9(55) = '1') AND (Gain_mul_temp_9(54 DOWNTO 51) /= "1111") ELSE
      Gain_mul_temp_9(51 DOWNTO 20);


  Sum1_op_stage1_gen: FOR t_05 IN 0 TO 9 GENERATE
    Sum1_stage2_add_cast(t_05) <= resize(I_ampa(t_05), 33);
    Sum1_stage2_add_cast_1(t_05) <= resize(I_gaba(t_05), 33);
    Sum1_stage2_add_temp(t_05) <= Sum1_stage2_add_cast(t_05) + Sum1_stage2_add_cast_1(t_05);
    
    Sum1_stage2_cast(t_05) <= X"7FFFFFFF" WHEN (Sum1_stage2_add_temp(t_05)(32) = '0') AND (Sum1_stage2_add_temp(t_05)(31) /= '0') ELSE
        X"80000000" WHEN (Sum1_stage2_add_temp(t_05)(32) = '1') AND (Sum1_stage2_add_temp(t_05)(31) /= '1') ELSE
        Sum1_stage2_add_temp(t_05)(31 DOWNTO 0);
    Sum1_op_stage1(t_05) <= resize(Sum1_stage2_cast(t_05), 33);
  END GENERATE Sum1_op_stage1_gen;


  Sum1_stage3_v <= resize(I_ext_signed, 32);

  Sum1_out1_gen: FOR t_06 IN 0 TO 9 GENERATE
    
    Sum1_stage3_add_cast(t_06) <= X"7FFFFFFF" WHEN (Sum1_op_stage1(t_06)(32) = '0') AND (Sum1_op_stage1(t_06)(31) /= '0') ELSE
        X"80000000" WHEN (Sum1_op_stage1(t_06)(32) = '1') AND (Sum1_op_stage1(t_06)(31) /= '1') ELSE
        Sum1_op_stage1(t_06)(31 DOWNTO 0);
    Sum1_stage3_add_cast_1(t_06) <= resize(Sum1_stage3_add_cast(t_06), 33);
    Sum1_stage3_add_cast_2(t_06) <= resize(Sum1_stage3_v, 33);
    Sum1_stage3_add_temp(t_06) <= Sum1_stage3_add_cast_1(t_06) + Sum1_stage3_add_cast_2(t_06);
    
    Sum1_out1(t_06) <= X"7FFFFFFF" WHEN (Sum1_stage3_add_temp(t_06)(32) = '0') AND (Sum1_stage3_add_temp(t_06)(31) /= '0') ELSE
        X"80000000" WHEN (Sum1_stage3_add_temp(t_06)(32) = '1') AND (Sum1_stage3_add_temp(t_06)(31) /= '1') ELSE
        Sum1_stage3_add_temp(t_06)(31 DOWNTO 0);
  END GENERATE Sum1_out1_gen;


  Current_Gain_mul_temp <= to_signed(16#000A3D#, 24) * Sum1_out1(0);
  
  Current_Gain_out1(0) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp(55) = '0') AND (Current_Gain_mul_temp(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp(55) = '1') AND (Current_Gain_mul_temp(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp(51 DOWNTO 20);
  Current_Gain_mul_temp_1 <= to_signed(16#000A3D#, 24) * Sum1_out1(1);
  
  Current_Gain_out1(1) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_1(55) = '0') AND (Current_Gain_mul_temp_1(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_1(55) = '1') AND (Current_Gain_mul_temp_1(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_1(51 DOWNTO 20);
  Current_Gain_mul_temp_2 <= to_signed(16#000A3D#, 24) * Sum1_out1(2);
  
  Current_Gain_out1(2) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_2(55) = '0') AND (Current_Gain_mul_temp_2(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_2(55) = '1') AND (Current_Gain_mul_temp_2(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_2(51 DOWNTO 20);
  Current_Gain_mul_temp_3 <= to_signed(16#000A3D#, 24) * Sum1_out1(3);
  
  Current_Gain_out1(3) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_3(55) = '0') AND (Current_Gain_mul_temp_3(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_3(55) = '1') AND (Current_Gain_mul_temp_3(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_3(51 DOWNTO 20);
  Current_Gain_mul_temp_4 <= to_signed(16#000A3D#, 24) * Sum1_out1(4);
  
  Current_Gain_out1(4) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_4(55) = '0') AND (Current_Gain_mul_temp_4(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_4(55) = '1') AND (Current_Gain_mul_temp_4(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_4(51 DOWNTO 20);
  Current_Gain_mul_temp_5 <= to_signed(16#000A3D#, 24) * Sum1_out1(5);
  
  Current_Gain_out1(5) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_5(55) = '0') AND (Current_Gain_mul_temp_5(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_5(55) = '1') AND (Current_Gain_mul_temp_5(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_5(51 DOWNTO 20);
  Current_Gain_mul_temp_6 <= to_signed(16#000A3D#, 24) * Sum1_out1(6);
  
  Current_Gain_out1(6) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_6(55) = '0') AND (Current_Gain_mul_temp_6(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_6(55) = '1') AND (Current_Gain_mul_temp_6(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_6(51 DOWNTO 20);
  Current_Gain_mul_temp_7 <= to_signed(16#000A3D#, 24) * Sum1_out1(7);
  
  Current_Gain_out1(7) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_7(55) = '0') AND (Current_Gain_mul_temp_7(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_7(55) = '1') AND (Current_Gain_mul_temp_7(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_7(51 DOWNTO 20);
  Current_Gain_mul_temp_8 <= to_signed(16#000A3D#, 24) * Sum1_out1(8);
  
  Current_Gain_out1(8) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_8(55) = '0') AND (Current_Gain_mul_temp_8(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_8(55) = '1') AND (Current_Gain_mul_temp_8(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_8(51 DOWNTO 20);
  Current_Gain_mul_temp_9 <= to_signed(16#000A3D#, 24) * Sum1_out1(9);
  
  Current_Gain_out1(9) <= X"7FFFFFFF" WHEN (Current_Gain_mul_temp_9(55) = '0') AND (Current_Gain_mul_temp_9(54 DOWNTO 51) /= "0000") ELSE
      X"80000000" WHEN (Current_Gain_mul_temp_9(55) = '1') AND (Current_Gain_mul_temp_9(54 DOWNTO 51) /= "1111") ELSE
      Current_Gain_mul_temp_9(51 DOWNTO 20);


  Sum_op_stage1_gen: FOR t_07 IN 0 TO 9 GENERATE
    Sum_stage2_add_cast(t_07) <= resize(Current_Gain_out1(t_07), 33);
    Sum_stage2_add_cast_1(t_07) <= resize(V_mem(t_07), 33);
    Sum_stage2_add_temp(t_07) <= Sum_stage2_add_cast(t_07) + Sum_stage2_add_cast_1(t_07);
    
    Sum_stage2_cast(t_07) <= X"7FFFFFFF" WHEN (Sum_stage2_add_temp(t_07)(32) = '0') AND (Sum_stage2_add_temp(t_07)(31) /= '0') ELSE
        X"80000000" WHEN (Sum_stage2_add_temp(t_07)(32) = '1') AND (Sum_stage2_add_temp(t_07)(31) /= '1') ELSE
        Sum_stage2_add_temp(t_07)(31 DOWNTO 0);
    Sum_op_stage1(t_07) <= resize(Sum_stage2_cast(t_07), 33);
  END GENERATE Sum_op_stage1_gen;



  Sum_out1_gen: FOR t_08 IN 0 TO 9 GENERATE
    
    Sum_stage3_add_cast(t_08) <= X"7FFFFFFF" WHEN (Sum_op_stage1(t_08)(32) = '0') AND (Sum_op_stage1(t_08)(31) /= '0') ELSE
        X"80000000" WHEN (Sum_op_stage1(t_08)(32) = '1') AND (Sum_op_stage1(t_08)(31) /= '1') ELSE
        Sum_op_stage1(t_08)(31 DOWNTO 0);
    Sum_stage3_add_cast_1(t_08) <= resize(Sum_stage3_add_cast(t_08), 33);
    Sum_stage3_add_cast_2(t_08) <= resize(Leakage_Gain_out1(t_08), 33);
    Sum_stage3_add_temp(t_08) <= Sum_stage3_add_cast_1(t_08) + Sum_stage3_add_cast_2(t_08);
    
    Sum_out1(t_08) <= X"7FFFFFFF" WHEN (Sum_stage3_add_temp(t_08)(32) = '0') AND (Sum_stage3_add_temp(t_08)(31) /= '0') ELSE
        X"80000000" WHEN (Sum_stage3_add_temp(t_08)(32) = '1') AND (Sum_stage3_add_temp(t_08)(31) /= '1') ELSE
        Sum_stage3_add_temp(t_08)(31 DOWNTO 0);
  END GENERATE Sum_out1_gen;


  Sum_out1_0 <= Sum_out1(0);

  Relational_Operator_out1_0 <= Relational_Operator_out1(0);

  
  Switch_out1_0 <= Sum_out1_0 WHEN Relational_Operator_out1_0 = '0' ELSE
      Constant_out1;

  Unit_Delay_out1_0 <= Unit_Delay_out1(0);

  
  switch_compare_1 <= '1' WHEN Unit_Delay_out1_0 > '0' ELSE
      '0';

  
  Switch2_out1_0 <= Switch_out1_0 WHEN switch_compare_1 = '0' ELSE
      Constant5_out1;

  Saturation_out1_9 <= Saturation_out1(9);

  Relational_Operator_out1_9_1 <= Relational_Operator_out1(9);

  
  switch_compare_10_2 <= '1' WHEN Relational_Operator_out1_9_1 > '0' ELSE
      '0';

  
  Switch1_out1_9 <= Saturation_out1_9 WHEN switch_compare_10_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_8 <= Saturation_out1(8);

  Relational_Operator_out1_8_1 <= Relational_Operator_out1(8);

  
  switch_compare_9_2 <= '1' WHEN Relational_Operator_out1_8_1 > '0' ELSE
      '0';

  
  Switch1_out1_8 <= Saturation_out1_8 WHEN switch_compare_9_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_7 <= Saturation_out1(7);

  Relational_Operator_out1_7_1 <= Relational_Operator_out1(7);

  
  switch_compare_8_2 <= '1' WHEN Relational_Operator_out1_7_1 > '0' ELSE
      '0';

  
  Switch1_out1_7 <= Saturation_out1_7 WHEN switch_compare_8_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_6 <= Saturation_out1(6);

  Relational_Operator_out1_6_1 <= Relational_Operator_out1(6);

  
  switch_compare_7_2 <= '1' WHEN Relational_Operator_out1_6_1 > '0' ELSE
      '0';

  
  Switch1_out1_6 <= Saturation_out1_6 WHEN switch_compare_7_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_5 <= Saturation_out1(5);

  Relational_Operator_out1_5_1 <= Relational_Operator_out1(5);

  
  switch_compare_6_2 <= '1' WHEN Relational_Operator_out1_5_1 > '0' ELSE
      '0';

  
  Switch1_out1_5 <= Saturation_out1_5 WHEN switch_compare_6_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_4 <= Saturation_out1(4);

  Relational_Operator_out1_4_1 <= Relational_Operator_out1(4);

  
  switch_compare_5_2 <= '1' WHEN Relational_Operator_out1_4_1 > '0' ELSE
      '0';

  
  Switch1_out1_4 <= Saturation_out1_4 WHEN switch_compare_5_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_3 <= Saturation_out1(3);

  Relational_Operator_out1_3_1 <= Relational_Operator_out1(3);

  
  switch_compare_4_2 <= '1' WHEN Relational_Operator_out1_3_1 > '0' ELSE
      '0';

  
  Switch1_out1_3 <= Saturation_out1_3 WHEN switch_compare_4_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_2 <= Saturation_out1(2);

  Relational_Operator_out1_2_1 <= Relational_Operator_out1(2);

  
  switch_compare_3_2 <= '1' WHEN Relational_Operator_out1_2_1 > '0' ELSE
      '0';

  
  Switch1_out1_2 <= Saturation_out1_2 WHEN switch_compare_3_2 = '0' ELSE
      Constant4_out1;

  Saturation_out1_1 <= Saturation_out1(1);

  Relational_Operator_out1_1_1 <= Relational_Operator_out1(1);

  
  switch_compare_2_2 <= '1' WHEN Relational_Operator_out1_1_1 > '0' ELSE
      '0';

  
  Switch1_out1_1 <= Saturation_out1_1 WHEN switch_compare_2_2 = '0' ELSE
      Constant4_out1;

  Refractory_Timer_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Refractory_Timer_out1 <= (OTHERS => to_signed(0, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Refractory_Timer_out1 <= Switch1_out1;
      END IF;
    END IF;
  END PROCESS Refractory_Timer_process;



  Add_out1_gen: FOR t_09 IN 0 TO 9 GENERATE
    Add_sub_cast(t_09) <= resize(Refractory_Timer_out1(t_09), 33);
    Add_sub_cast_1(t_09) <= resize(Constant3_out1, 33);
    Add_sub_temp(t_09) <= Add_sub_cast(t_09) - Add_sub_cast_1(t_09);
    
    Add_out1(t_09) <= X"7FFFFFFF" WHEN (Add_sub_temp(t_09)(32) = '0') AND (Add_sub_temp(t_09)(31) /= '0') ELSE
        X"80000000" WHEN (Add_sub_temp(t_09)(32) = '1') AND (Add_sub_temp(t_09)(31) /= '1') ELSE
        Add_sub_temp(t_09)(31 DOWNTO 0);
  END GENERATE Add_out1_gen;


  Saturation_output : PROCESS (Add_out1)
  BEGIN

    FOR ii IN 0 TO 9 LOOP
      IF Add_out1(ii) > to_signed(10240, 32) THEN 
        Saturation_out1(ii) <= to_signed(10240, 32);
      ELSIF Add_out1(ii) < to_signed(0, 32) THEN 
        Saturation_out1(ii) <= to_signed(0, 32);
      ELSE 
        Saturation_out1(ii) <= Add_out1(ii);
      END IF;
    END LOOP;

  END PROCESS Saturation_output;


  Saturation_out1_0 <= Saturation_out1(0);

  Relational_Operator_out1_0_1 <= Relational_Operator_out1(0);

  
  switch_compare_1_1 <= '1' WHEN Relational_Operator_out1_0_1 > '0' ELSE
      '0';

  
  Switch1_out1_0 <= Saturation_out1_0 WHEN switch_compare_1_1 = '0' ELSE
      Constant4_out1;

  Switch1_out1(0) <= Switch1_out1_0;
  Switch1_out1(1) <= Switch1_out1_1;
  Switch1_out1(2) <= Switch1_out1_2;
  Switch1_out1(3) <= Switch1_out1_3;
  Switch1_out1(4) <= Switch1_out1_4;
  Switch1_out1(5) <= Switch1_out1_5;
  Switch1_out1(6) <= Switch1_out1_6;
  Switch1_out1(7) <= Switch1_out1_7;
  Switch1_out1(8) <= Switch1_out1_8;
  Switch1_out1(9) <= Switch1_out1_9;


  Relational_Operator1_out1_gen: FOR t_010 IN 0 TO 9 GENERATE
    
    Relational_Operator1_out1(t_010) <= '1' WHEN Switch1_out1(t_010) > Constant7_out1 ELSE
        '0';
  END GENERATE Relational_Operator1_out1_gen;


  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Relational_Operator1_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Unit_Delay_out1_0_1 <= Unit_Delay_out1(0);

  
  switch_compare_1_2 <= '1' WHEN Unit_Delay_out1_0_1 > '0' ELSE
      '0';

  
  Switch3_out1_0 <= Switch2_out1_0 WHEN switch_compare_1_2 = '0' ELSE
      V_mem_0;

  Switch3_out1(0) <= Switch3_out1_0;
  Switch3_out1(1) <= Switch3_out1_1;
  Switch3_out1(2) <= Switch3_out1_2;
  Switch3_out1(3) <= Switch3_out1_3;
  Switch3_out1(4) <= Switch3_out1_4;
  Switch3_out1(5) <= Switch3_out1_5;
  Switch3_out1(6) <= Switch3_out1_6;
  Switch3_out1(7) <= Switch3_out1_7;
  Switch3_out1(8) <= Switch3_out1_8;
  Switch3_out1(9) <= Switch3_out1_9;

  V_mem_10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      V_mem <= (OTHERS => to_signed(-16640, 32));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        V_mem <= Switch3_out1;
      END IF;
    END IF;
  END PROCESS V_mem_10_process;



  Relational_Operator_out1_gen: FOR t_011 IN 0 TO 9 GENERATE
    
    Relational_Operator_out1(t_011) <= '1' WHEN V_mem(t_011) >= Constant6_out1 ELSE
        '0';
  END GENERATE Relational_Operator_out1_gen;


  Spike <= Relational_Operator_out1;

END rtl;

