-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\MATLAB_Function.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/MATLAB Function
-- Hierarchy Level: 1
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MMN_Core_Chip_pkg.ALL;

ENTITY MATLAB_Function IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        spikes_pre                        :   IN    std_logic_vector(99 DOWNTO 0);  -- boolean [100]
        spikes_post                       :   IN    std_logic_vector(9 DOWNTO 0);  -- boolean [10]
        I_syn                             :   OUT   vector_of_std_logic_vector16(0 TO 9)  -- sfix16_En8 [10]
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Signals
  SIGNAL weights_reg_ctrl_const_out       : std_logic;
  SIGNAL weights_reg_ctrl_delay_out       : std_logic;
  SIGNAL c42_weights_reg_Initial_Val_out  : vector_of_signed16(0 TO 999);  -- sfix16_En8 [1000]
  SIGNAL tmp                              : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL trace_pre                        : vector_of_signed18(0 TO 99);  -- sfix18_En17 [100]
  SIGNAL trace_pre_1                      : vector_of_signed18(0 TO 99);  -- sfix18_En17 [100]
  SIGNAL trace_pre_2                      : vector_of_signed18(0 TO 99);  -- sfix18_En17 [100]
  SIGNAL tmp_1                            : signed(17 DOWNTO 0);  -- sfix18_En17
  SIGNAL trace_post                       : vector_of_signed18(0 TO 9);  -- sfix18_En17 [10]
  SIGNAL trace_post_1                     : vector_of_signed18(0 TO 9);  -- sfix18_En17 [10]
  SIGNAL trace_post_2                     : vector_of_signed18(0 TO 9);  -- sfix18_En17 [10]
  SIGNAL weights                          : matrix_of_signed16(0 TO 9, 0 TO 99);  -- sfix16_En8 [10x100]
  SIGNAL c36_weights                      : vector_of_signed16(0 TO 999);  -- sfix16_En8 [1000]
  SIGNAL c36_weights_reg_out              : vector_of_signed16(0 TO 999);  -- sfix16_En8 [1000]
  SIGNAL c45_weights                      : vector_of_signed16(0 TO 999);  -- sfix16_En8 [1000]
  SIGNAL weights_1                        : matrix_of_signed16(0 TO 9, 0 TO 99);  -- sfix16_En8 [10x100]
  SIGNAL I_syn_tmp                        : vector_of_signed16(0 TO 9);  -- sfix16_En8 [10]

BEGIN
  weights_reg_ctrl_const_out <= '1';

  weights_reg_ctrl_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      weights_reg_ctrl_delay_out <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        weights_reg_ctrl_delay_out <= weights_reg_ctrl_const_out;
      END IF;
    END IF;
  END PROCESS weights_reg_ctrl_delay_process;


  c42_weights_reg_Initial_Val_out <= (OTHERS => to_signed(16#0066#, 16));

  tmp <= to_signed(16#00000#, 18);

  p5_output : PROCESS (spikes_pre, trace_pre)
    VARIABLE trace_pre1 : signed(17 DOWNTO 0);
    VARIABLE add_cast : signed(31 DOWNTO 0);
    VARIABLE add_temp : signed(31 DOWNTO 0);
  BEGIN
    trace_pre1 := to_signed(16#00000#, 18);
    add_temp := to_signed(0, 32);
    add_cast := to_signed(0, 32);

    FOR j IN 0 TO 99 LOOP
      IF spikes_pre(j) = '1' THEN 
        add_cast := resize(trace_pre(j) & '0' & '0' & '0', 32);
        add_temp := add_cast + to_signed(20968, 32);
        IF ((add_temp(31) = '0') AND (add_temp(30 DOWNTO 20) /= "00000000000")) OR ((add_temp(31) = '0') AND (add_temp(20 DOWNTO 3) = "011111111111111111")) THEN 
          trace_pre1 := "011111111111111111";
        ELSIF (add_temp(31) = '1') AND (add_temp(30 DOWNTO 20) /= "11111111111") THEN 
          trace_pre1 := "100000000000000000";
        ELSE 
          trace_pre1 := add_temp(20 DOWNTO 3) + ('0' & add_temp(2));
        END IF;
      ELSE 
        trace_pre1 := trace_pre(j);
      END IF;
      trace_pre_1(j) <= trace_pre1;
    END LOOP;

  END PROCESS p5_output;


  trace_pre_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      trace_pre_2 <= (OTHERS => to_signed(16#00000#, 18));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        trace_pre_2 <= trace_pre_1;
      END IF;
    END IF;
  END PROCESS trace_pre_reg_process;


  p9_output : PROCESS (tmp, trace_pre_2)
    VARIABLE trace_pre2 : signed(17 DOWNTO 0);
    VARIABLE trace_pre_0 : signed(17 DOWNTO 0);
    VARIABLE mul_temp : signed(35 DOWNTO 0);
    VARIABLE cast : signed(31 DOWNTO 0);
  BEGIN
    trace_pre_0 := to_signed(16#00000#, 18);
    mul_temp := to_signed(0, 36);
    cast := to_signed(0, 32);
    trace_pre2 := to_signed(16#00000#, 18);

    FOR j1 IN 0 TO 99 LOOP
      mul_temp := trace_pre_2(j1) * to_signed(16#1FDDF#, 18);
      cast := (resize(mul_temp(35 DOWNTO 14), 32)) + ('0' & mul_temp(13));
      IF ((cast(31) = '0') AND (cast(30 DOWNTO 20) /= "00000000000")) OR ((cast(31) = '0') AND (cast(20 DOWNTO 3) = "011111111111111111")) THEN 
        trace_pre2 := "011111111111111111";
      ELSIF (cast(31) = '1') AND (cast(30 DOWNTO 20) /= "11111111111") THEN 
        trace_pre2 := "100000000000000000";
      ELSE 
        trace_pre2 := cast(20 DOWNTO 3) + ('0' & cast(2));
      END IF;
      IF trace_pre2 < to_signed(16#00162#, 18) THEN 
        trace_pre_0 := tmp;
      ELSE 
        trace_pre_0 := trace_pre2;
      END IF;
      trace_pre(j1) <= trace_pre_0;
    END LOOP;

  END PROCESS p9_output;


  tmp_1 <= to_signed(16#00000#, 18);

  p3_output : PROCESS (spikes_post, trace_post)
    VARIABLE trace_post1 : signed(17 DOWNTO 0);
    VARIABLE sub_cast : signed(31 DOWNTO 0);
    VARIABLE sub_temp : signed(31 DOWNTO 0);
  BEGIN
    trace_post1 := to_signed(16#00000#, 18);
    sub_temp := to_signed(0, 32);
    sub_cast := to_signed(0, 32);

    FOR i IN 0 TO 9 LOOP
      IF spikes_post(i) = '1' THEN 
        sub_cast := resize(trace_post(i) & '0' & '0' & '0', 32);
        sub_temp := sub_cast - to_signed(31456, 32);
        IF ((sub_temp(31) = '0') AND (sub_temp(30 DOWNTO 20) /= "00000000000")) OR ((sub_temp(31) = '0') AND (sub_temp(20 DOWNTO 3) = "011111111111111111")) THEN 
          trace_post1 := "011111111111111111";
        ELSIF (sub_temp(31) = '1') AND (sub_temp(30 DOWNTO 20) /= "11111111111") THEN 
          trace_post1 := "100000000000000000";
        ELSE 
          trace_post1 := sub_temp(20 DOWNTO 3) + ('0' & sub_temp(2));
        END IF;
      ELSE 
        trace_post1 := trace_post(i);
      END IF;
      trace_post_1(i) <= trace_post1;
    END LOOP;

  END PROCESS p3_output;


  trace_post_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      trace_post_2 <= (OTHERS => to_signed(16#00000#, 18));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        trace_post_2 <= trace_post_1;
      END IF;
    END IF;
  END PROCESS trace_post_reg_process;


  p8_output : PROCESS (tmp_1, trace_post_2)
    VARIABLE trace_post2 : signed(17 DOWNTO 0);
    VARIABLE trace_post_0 : signed(17 DOWNTO 0);
    VARIABLE mul_temp1 : signed(35 DOWNTO 0);
    VARIABLE cast1 : signed(31 DOWNTO 0);
  BEGIN
    trace_post_0 := to_signed(16#00000#, 18);
    mul_temp1 := to_signed(0, 36);
    cast1 := to_signed(0, 32);
    trace_post2 := to_signed(16#00000#, 18);

    FOR i1 IN 0 TO 9 LOOP
      mul_temp1 := trace_post_2(i1) * to_signed(16#1FEEF#, 18);
      cast1 := (resize(mul_temp1(35 DOWNTO 14), 32)) + ('0' & mul_temp1(13));
      IF ((cast1(31) = '0') AND (cast1(30 DOWNTO 20) /= "00000000000")) OR ((cast1(31) = '0') AND (cast1(20 DOWNTO 3) = "011111111111111111")) THEN 
        trace_post2 := "011111111111111111";
      ELSIF (cast1(31) = '1') AND (cast1(30 DOWNTO 20) /= "11111111111") THEN 
        trace_post2 := "100000000000000000";
      ELSE 
        trace_post2 := cast1(20 DOWNTO 3) + ('0' & cast1(2));
      END IF;
      IF trace_post2 > to_signed(-16#0083E#, 18) THEN 
        trace_post_0 := tmp_1;
      ELSE 
        trace_post_0 := trace_post2;
      END IF;
      trace_post(i1) <= trace_post_0;
    END LOOP;

  END PROCESS p8_output;


  c36_weights_gen1: FOR d1 IN 0 TO 99 GENERATE
    c36_weights_gen: FOR d0 IN 0 TO 9 GENERATE
      c36_weights(d0 + (d1 * 10)) <= weights(d0, d1);
    END GENERATE;
  END GENERATE;

  weights_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      c36_weights_reg_out <= (OTHERS => to_signed(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        c36_weights_reg_out <= c36_weights;
      END IF;
    END IF;
  END PROCESS weights_reg_process;


  
  c45_weights <= c42_weights_reg_Initial_Val_out WHEN weights_reg_ctrl_delay_out = '0' ELSE
      c36_weights_reg_out;

  weights_1_gen1: FOR d1 IN 0 TO 99 GENERATE
    weights_1_gen: FOR d0 IN 0 TO 9 GENERATE
      weights_1(d0, d1) <= c45_weights(d0 + (d1 * 10));
    END GENERATE;
  END GENERATE;

  p7_output : PROCESS (spikes_post, spikes_pre, trace_post, trace_pre, weights_1)
    VARIABLE weights1 : matrix_of_signed16(0 TO 9, 0 TO 99);
    VARIABLE I_syn1 : vector_of_signed16(0 TO 9);
    VARIABLE toplam : signed(15 DOWNTO 0);
    VARIABLE tmp1 : signed(15 DOWNTO 0);
    VARIABLE tmp_0 : signed(15 DOWNTO 0);
    VARIABLE tmp_11 : signed(15 DOWNTO 0);
    VARIABLE tmp_2 : signed(15 DOWNTO 0);
    VARIABLE toplam_0 : signed(15 DOWNTO 0);
    VARIABLE add_cast1 : signed(31 DOWNTO 0);
    VARIABLE add_cast_0 : signed(15 DOWNTO 0);
    VARIABLE add_cast_1 : signed(31 DOWNTO 0);
    VARIABLE add_temp1 : signed(31 DOWNTO 0);
    VARIABLE add_cast_2 : signed(31 DOWNTO 0);
    VARIABLE add_cast_3 : signed(33 DOWNTO 0);
    VARIABLE add_cast_4 : signed(31 DOWNTO 0);
    VARIABLE add_cast_5 : signed(15 DOWNTO 0);
    VARIABLE add_cast_6 : signed(31 DOWNTO 0);
    VARIABLE add_temp_0 : signed(31 DOWNTO 0);
    VARIABLE add_cast_7 : signed(31 DOWNTO 0);
    VARIABLE add_cast_8 : signed(31 DOWNTO 0);
    VARIABLE add_temp_1 : signed(31 DOWNTO 0);
  BEGIN
    toplam := to_signed(16#0000#, 16);
    tmp1 := to_signed(16#0000#, 16);
    tmp_0 := to_signed(16#0000#, 16);
    tmp_11 := to_signed(16#0000#, 16);
    tmp_2 := to_signed(16#0000#, 16);
    toplam_0 := to_signed(16#0000#, 16);
    add_temp1 := to_signed(0, 32);
    add_temp_0 := to_signed(0, 32);
    add_temp_1 := to_signed(0, 32);
    add_cast1 := to_signed(0, 32);
    add_cast_0 := to_signed(16#0000#, 16);
    add_cast_1 := to_signed(0, 32);
    add_cast_2 := to_signed(0, 32);
    add_cast_3 := to_signed(0, 34);
    add_cast_4 := to_signed(0, 32);
    add_cast_5 := to_signed(16#0000#, 16);
    add_cast_6 := to_signed(0, 32);
    add_cast_7 := to_signed(0, 32);
    add_cast_8 := to_signed(0, 32);
    weights1 := weights_1;

    FOR r IN 0 TO 9 LOOP
      toplam := to_signed(16#0000#, 16);

      FOR c IN 0 TO 99 LOOP
        IF spikes_post(r) = '1' THEN 
          add_cast1 := resize(weights1(r, c) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
          add_cast_0 := (resize(trace_pre(c)(17 DOWNTO 9), 16)) + ('0' & trace_pre(c)(8));
          add_cast_1 := resize(add_cast_0 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
          add_temp1 := add_cast1 + add_cast_1;
          IF ((add_temp1(31) = '0') AND (add_temp1(30 DOWNTO 27) /= "0000")) OR ((add_temp1(31) = '0') AND (add_temp1(27 DOWNTO 12) = X"7FFF")) THEN 
            tmp1 := X"7FFF";
          ELSIF (add_temp1(31) = '1') AND (add_temp1(30 DOWNTO 27) /= "1111") THEN 
            tmp1 := X"8000";
          ELSE 
            tmp1 := add_temp1(27 DOWNTO 12) + ('0' & add_temp1(11));
          END IF;
        ELSE 
          tmp1 := weights1(r, c);
        END IF;
        IF spikes_pre(c) = '1' THEN 
          add_cast_2 := resize(tmp1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
          add_cast_3 := resize(trace_post(r) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34);
          add_cast_4 := (resize(add_cast_3(33 DOWNTO 5), 32)) + ('0' & add_cast_3(4));
          IF ((add_cast_4(31) = '0') AND (add_cast_4(30 DOWNTO 27) /= "0000")) OR ((add_cast_4(31) = '0') AND (add_cast_4(27 DOWNTO 12) = X"7FFF")) THEN 
            add_cast_5 := X"7FFF";
          ELSIF (add_cast_4(31) = '1') AND (add_cast_4(30 DOWNTO 27) /= "1111") THEN 
            add_cast_5 := X"8000";
          ELSE 
            add_cast_5 := add_cast_4(27 DOWNTO 12) + ('0' & add_cast_4(11));
          END IF;
          add_cast_6 := resize(add_cast_5 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
          add_temp_0 := add_cast_2 + add_cast_6;
          IF ((add_temp_0(31) = '0') AND (add_temp_0(30 DOWNTO 27) /= "0000")) OR ((add_temp_0(31) = '0') AND (add_temp_0(27 DOWNTO 12) = X"7FFF")) THEN 
            tmp_0 := X"7FFF";
          ELSIF (add_temp_0(31) = '1') AND (add_temp_0(30 DOWNTO 27) /= "1111") THEN 
            tmp_0 := X"8000";
          ELSE 
            tmp_0 := add_temp_0(27 DOWNTO 12) + ('0' & add_temp_0(11));
          END IF;
        ELSE 
          tmp_0 := tmp1;
        END IF;
        IF tmp_0 < to_signed(16#0003#, 16) THEN 
          tmp_11 := to_signed(16#0003#, 16);
        ELSE 
          tmp_11 := tmp_0;
        END IF;
        IF tmp_0 > to_signed(16#0A00#, 16) THEN 
          tmp_2 := to_signed(16#0A00#, 16);
        ELSE 
          tmp_2 := tmp_11;
        END IF;
        weights1(r, c) := tmp_2;
        IF spikes_pre(c) = '1' THEN 
          add_cast_7 := resize(toplam & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
          add_cast_8 := resize(tmp_2 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);
          add_temp_1 := add_cast_7 + add_cast_8;
          IF ((add_temp_1(31) = '0') AND (add_temp_1(30 DOWNTO 27) /= "0000")) OR ((add_temp_1(31) = '0') AND (add_temp_1(27 DOWNTO 12) = X"7FFF")) THEN 
            toplam_0 := X"7FFF";
          ELSIF (add_temp_1(31) = '1') AND (add_temp_1(30 DOWNTO 27) /= "1111") THEN 
            toplam_0 := X"8000";
          ELSE 
            toplam_0 := add_temp_1(27 DOWNTO 12) + ('0' & add_temp_1(11));
          END IF;
        ELSE 
          toplam_0 := toplam;
        END IF;
        toplam := toplam_0;
      END LOOP;

      I_syn1(r) := toplam;
    END LOOP;

    weights <= weights1;
    I_syn_tmp <= I_syn1;
  END PROCESS p7_output;


  outputgen: FOR k IN 0 TO 9 GENERATE
    I_syn(k) <= std_logic_vector(I_syn_tmp(k));
  END GENERATE;

END rtl;

