-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\Mem_A.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Mem_A
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/Mem_A
-- Hierarchy Level: 1
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Mem_A IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In_AMPA                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        In_GABA                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        I_ext                             :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        Spike                             :   OUT   std_logic
        );
END Mem_A;


ARCHITECTURE rtl OF Mem_A IS

  -- Component Declarations
  COMPONENT AMPA_Synapse_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Spike_Weight                    :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          s_ampa_out                      :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En8
          );
  END COMPONENT;

  COMPONENT GABA_Synapse_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Spike_Weight1                   :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          s_gaba_out                      :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En8
          );
  END COMPONENT;

  COMPONENT LIF_Neuron_Conductance_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          s_ampa                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          s_gaba                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          I_ext                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          Spike                           :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : AMPA_Synapse_block
    USE ENTITY work.AMPA_Synapse_block(rtl);

  FOR ALL : GABA_Synapse_block
    USE ENTITY work.GABA_Synapse_block(rtl);

  FOR ALL : LIF_Neuron_Conductance_block
    USE ENTITY work.LIF_Neuron_Conductance_block(rtl);

  -- Signals
  SIGNAL AMPA_Synapse_s_ampa_out          : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL GABA_Synapse_s_gaba_out          : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL LIF_Neuron_Conductance_Spike     : std_logic;

BEGIN
  u_AMPA_Synapse : AMPA_Synapse_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Spike_Weight => In_AMPA,  -- sfix24_En8
              s_ampa_out => AMPA_Synapse_s_ampa_out  -- sfix24_En8
              );

  u_GABA_Synapse : GABA_Synapse_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Spike_Weight1 => In_GABA,  -- sfix24_En8
              s_gaba_out => GABA_Synapse_s_gaba_out  -- sfix24_En8
              );

  u_LIF_Neuron_Conductance : LIF_Neuron_Conductance_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              s_ampa => AMPA_Synapse_s_ampa_out,  -- sfix24_En8
              s_gaba => GABA_Synapse_s_gaba_out,  -- sfix24_En8
              I_ext => I_ext,  -- sfix24_En8
              Spike => LIF_Neuron_Conductance_Spike
              );

  Spike <= LIF_Neuron_Conductance_Spike;

END rtl;

