-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mmn_kart_candidate1_hdl\P_A.vhd
-- Created: 2026-05-01 03:13:21
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: P_A
-- Source Path: mmn_kart_candidate1_hdl/MMN_Core_Chip/P_A
-- Hierarchy Level: 1
-- Model version: 1.25
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.MMN_Core_Chip_pkg.ALL;

ENTITY P_A IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In_AMPA                           :   IN    vector_of_std_logic_vector24(0 TO 9);  -- sfix24_En8 [10]
        In_GABA                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
        Spike                             :   OUT   std_logic_vector(9 DOWNTO 0)  -- boolean [10]
        );
END P_A;


ARCHITECTURE rtl OF P_A IS

  -- Component Declarations
  COMPONENT AMPA_Synapse_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Spike_Weight                    :   IN    vector_of_std_logic_vector24(0 TO 9);  -- sfix24_En8 [10]
          s_ampa_out                      :   OUT   vector_of_std_logic_vector24(0 TO 9)  -- sfix24_En8 [10]
          );
  END COMPONENT;

  COMPONENT GABA_Synapse_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Spike_Weight1                   :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          s_gaba_out                      :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En8
          );
  END COMPONENT;

  COMPONENT LIF_Neuron_Conductance_block2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          s_ampa                          :   IN    vector_of_std_logic_vector24(0 TO 9);  -- sfix24_En8 [10]
          s_gaba                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          I_ext                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En8
          Spike                           :   OUT   std_logic_vector(9 DOWNTO 0)  -- boolean [10]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : AMPA_Synapse_block2
    USE ENTITY work.AMPA_Synapse_block2(rtl);

  FOR ALL : GABA_Synapse_block2
    USE ENTITY work.GABA_Synapse_block2(rtl);

  FOR ALL : LIF_Neuron_Conductance_block2
    USE ENTITY work.LIF_Neuron_Conductance_block2(rtl);

  -- Signals
  SIGNAL In_AMPA_signed                   : vector_of_signed24(0 TO 9);  -- sfix24_En8 [10]
  SIGNAL Variable_Integer_Delay_reg       : vector_of_signed24(0 TO 1499);  -- sfix24 [1500]
  SIGNAL Variable_Integer_Delay_out1      : vector_of_signed24(0 TO 9);  -- sfix24_En8 [10]
  SIGNAL Variable_Integer_Delay_out1_1    : vector_of_std_logic_vector24(0 TO 9);  -- ufix24 [10]
  SIGNAL AMPA_Synapse_s_ampa_out          : vector_of_std_logic_vector24(0 TO 9);  -- ufix24 [10]
  SIGNAL In_GABA_signed                   : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL Variable_Integer_Delay1_reg      : vector_of_signed24(0 TO 149);  -- sfix24 [150]
  SIGNAL Variable_Integer_Delay1_out1     : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL GABA_Synapse_s_gaba_out          : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL Constant_out1                    : signed(23 DOWNTO 0);  -- sfix24_En8
  SIGNAL LIF_Neuron_Conductance_Spike     : std_logic_vector(9 DOWNTO 0);  -- boolean [10]

BEGIN
  u_AMPA_Synapse : AMPA_Synapse_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Spike_Weight => Variable_Integer_Delay_out1_1,  -- sfix24_En8 [10]
              s_ampa_out => AMPA_Synapse_s_ampa_out  -- sfix24_En8 [10]
              );

  u_GABA_Synapse : GABA_Synapse_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Spike_Weight1 => std_logic_vector(Variable_Integer_Delay1_out1),  -- sfix24_En8
              s_gaba_out => GABA_Synapse_s_gaba_out  -- sfix24_En8
              );

  u_LIF_Neuron_Conductance : LIF_Neuron_Conductance_block2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              s_ampa => AMPA_Synapse_s_ampa_out,  -- sfix24_En8 [10]
              s_gaba => GABA_Synapse_s_gaba_out,  -- sfix24_En8
              I_ext => std_logic_vector(Constant_out1),  -- sfix24_En8
              Spike => LIF_Neuron_Conductance_Spike  -- boolean [10]
              );

  outputgen1: FOR k IN 0 TO 9 GENERATE
    In_AMPA_signed(k) <= signed(In_AMPA(k));
  END GENERATE;

  Variable_Integer_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Variable_Integer_Delay_reg <= (OTHERS => to_signed(16#000000#, 24));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Variable_Integer_Delay_reg(0 TO 9) <= In_AMPA_signed(0 TO 9);
        Variable_Integer_Delay_reg(10 TO 1499) <= Variable_Integer_Delay_reg(0 TO 1489);
      END IF;
    END IF;
  END PROCESS Variable_Integer_Delay_process;

  Variable_Integer_Delay_out1(0 TO 9) <= Variable_Integer_Delay_reg(1490 TO 1499);

  outputgen: FOR k IN 0 TO 9 GENERATE
    Variable_Integer_Delay_out1_1(k) <= std_logic_vector(Variable_Integer_Delay_out1(k));
  END GENERATE;

  In_GABA_signed <= signed(In_GABA);

  Variable_Integer_Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Variable_Integer_Delay1_reg <= (OTHERS => to_signed(16#000000#, 24));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Variable_Integer_Delay1_reg(0) <= In_GABA_signed;
        Variable_Integer_Delay1_reg(1 TO 149) <= Variable_Integer_Delay1_reg(0 TO 148);
      END IF;
    END IF;
  END PROCESS Variable_Integer_Delay1_process;

  Variable_Integer_Delay1_out1 <= Variable_Integer_Delay1_reg(149);

  Constant_out1 <= to_signed(16#000000#, 24);

  Spike <= LIF_Neuron_Conductance_Spike;

END rtl;

